### ISSUE TITLE
[Feature Request] Enable directory mounts for local read/write

### ISSUE THREAD

**Issue by yannick-vinkesteijn** [vantage6/vantage6#1172]
**Problem description**
Currently Vantage6 only supports file/db mounts, however our train/inference pipelines often need to store multiple checkpoint and result files with content that can't leave the server. Because each node has their own type of after processing of inference results, we use csv files and can't use a more flexible setup like a database.

**Desired solution**
Enable directory mounts with read/write access to support complex inference/train pipelines and local checkpoint saves.

**Comment by harmbuisman** [comment]
We have a similar request where we can use a mounted folder to write to the file system of the machine that runs a node (see bottom left). One use case for this is for example to make and store local predicitions using a federated prediction model. 

![image](https://github.com/vantage6/vantage6/assets/7702207/f21404da-b91e-4bf1-b496-b1df1c226bd7)

**Comment by frankcorneliusmartin** [comment]
@yannick-vinkesteijn 

* You need a bilateral way to exchange data between the vantage6-node and the EPD?
* The files that are provided are always in CSV format?
* Which format is provided from the vantage6 node to the EPD?
* Does the hospitals upload the data using the FTP protocol or something similar? 
* Could it be possible to deliver the files through a HTTP service? (e.g. to a POST `/files` endpoint?)

Sorry for asking so many questions, but I want to understand the problem so we can provided an appropriate solution.

**Comment by yannick-vinkesteijn** [comment]
@frankcorneliusmartin sorry my notifications did not work.
- You need a bilateral way to exchange data between the vantage6-node and the EPD?
    _Yes because we read the files from the local server and write output files back to the server_
- The files that are provided are always in CSV format?
    _Some hospitals also give us jsons or excel files but these are exceptions_
- Which format is provided from the vantage6 node to the EPD?
    _Currently we return csv files to the server that are then further processed by the hospital. It depends per hospital if they have an automated export to EPD pipeline or do this by hand._
- Does the hospitals upload the data using the FTP protocol or something similar?
    _It depends per hospital how they do this. Some use a shared disk that has some scheduler attached others move the file manually each time we generate output. Because of the difference in automation and setup we just create a csv and are not responsible for the export to EPD part of the pipeline._
- Could it be possible to deliver the files through a HTTP service? (e.g. to a POST /files endpoint?)
    _Not all hospitals have the infrastructure or knowledge to setup or use such a service unfortunately. Also some hospitals work with strict http/https whitelisting for incoming/outgoing traffic, so i'm not sure if this adds complexity to the firewall setup?_

**Comment by dkapitan** [comment]
@frankcorneliusmartin @yannick-vinkesteijn @harmbuisman: perhaps this is a possible solution design?

- Vantage6 supports [mapping of the `host-gateway`](https://docs.vantage6.ai/en/main/node/configure.html#all-configuration-options). More documentation [here](https://docs.docker.com/reference/cli/docker/container/run/#add-host).
- [fsspec](https://filesystem-spec.readthedocs.io/en/latest/#) supports various filesystem abstractions, amongst which
  -  [simple HttpFs](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.implementations.http.HTTPFileSystem) (read-only)
  - [Samba](https://filesystem-spec.readthedocs.io/en/latest/api.html#fsspec.implementations.smb.SMBFileSystem) (read + write)
  - [WebDAV](https://github.com/skshetry/webdav4) (read + write)

So wouldn't it be the most straightforward solution to:
- turn on the Apache server on the Linux host machine and configure web-dav ([how-to](https://linuxconfig.org/webdav-server-setup-on-ubuntu-linux))
- add the `host-gateway` to the node

**Comment by bartvanb** [comment]
If I understand correctly, your main goal is for your *algorithms* (rather than the *node*) to be aware of the latest data on the hard drive disk, right?

Obviously then it makes sense that the node should be given access since it usually is a separation layer between the host and the algorithm. However, I was wondering if we could use the [whitelisting](https://docs.vantage6.ai/en/main/features/node/whitelisting.html) feature to allow the algorithm container access to the host system. This access would go via a squid proxy, which supports HTTP(S) (which is I think why @frankcorneliusmartin asked about whether a HTTP service could be set up at the node). Squid can also support FTP (not sure if we use that in vantage6 atm though).

@dkapitan I think using that option, you could go over the node and directly have the algorithm container talk to the host system. I haven't looked into fsspec and whether that would work, but I just wanted to make you aware of that option.

Note also that if you use the whitelisting option to the host, you are giving all algorithms that are run on the node access to the host - so then it is extra important to make sure that no malicious algorithms can be run

**Comment by dkapitan** [comment]
@bartvanb thanks for the swift response. Indeed the scenario is that the node has access to the latest data on the Linux host machine. In our architecture, we envisage a datastation using Apache Iceberg and parquet files.

We will investigate whitelisting and the `host-gateway` solution and let you know which works.

**Comment by dkapitan** [comment]
@yannick-vinkesteijn @bartvanb @mellesies 

We have had quite a few discussions, and in the end we were kind of meaning to say the same but got lost in the differences between how Docker interfaces with the host filesystem depending on whether you use Linux, Mac or Windows.

So this is the proposed solution:

![webdav-docker-engine](https://github.com/vantage6/vantage6/assets/4090894/6a05ba5f-e71d-4ce6-92ed-1fcb849a30f7)

- We standardize on Linux + Docker Engine, because **volume mounts from any container running on the host is accesible on the host machine, even if the container is not running**. This transparency is only provided in Linux, because Docker Engine runs directly on the kernel and uses Linux namespaces. Docker volumes can not be accessed directly from the host machine on Windows or Mac.
- We run a WebDAV container

**Comment by dkapitan** [comment]
@yannick-vinkesteijn @bartvanb @mellesies 

We have had quite a few discussions, and in the end we were kind of meaning to say the same but got lost in the differences between how Docker interfaces with the host filesystem depending on whether you use Linux, Mac or Windows.

So this is the proposed solution:

![webdav-docker-engine](https://github.com/vantage6/vantage6/assets/4090894/6a05ba5f-e71d-4ce6-92ed-1fcb849a30f7)

- We standardize on Linux + Docker Engine, because **volume mounts from any container running on the host is accesible on the host machine, even if the container is not running**. This transparency is only provided in Linux, because Docker Engine runs directly on the kernel and uses Linux namespaces. Docker volumes can not be accessed directly from the host machine on Windows or Mac.
- We run a WebDAV container next to the vantage6 node and connect those via the IP whitelisting mechanism in vantage6
- This solution design allows to even have different WebDAV services (mapped to different folders on the host) for different projects
- Because of storage on disk is directly accessible from the host, we can apply Linux' access right mechanisms on the file system, to optimize security and integrity.

Happy to hear your feedback on this. And if it helps, I am happy to contribute to the documentation of vantage6, such that our setup, scripts etc. are also available to the community.

**Comment by bartvanb** [comment]
I think that could work. @mellesies also had the idea that instead of whitelisting, the [docker service linking feature](https://docs.vantage6.ai/en/main/features/node/linked_docker_service.html) may be useful, as it is maybe easier to configure. That feature would also make the webdav container available to algorithm containers.

Perhaps also good to discuss this at some point in a meeting - I am afraid I am otherwise overlooking things as we have multiple and rather complex options available.

**Comment by dkapitan** [comment]
Thanks for this, @bartvanb. Will definitely take you up on your offer to have a meeting. We are going to do some testing first and happy to share our findings.

**Comment by dkapitan** [comment]
@yannick-vinkesteijn @bartvanb 

Just for completeness sake, hereby the solution.

First, given the following Dockerfile for a rootless Apache server that we want to run on the same host that runs the node:

```
# Use the official Apache HTTP Server image
FROM httpd:latest

# UID and GID default to 1000 if not given
ARG UID=1000
ARG GID=1000

# Install basic tools for debugging
RUN apt-get update && \
    apt-get install -y nano curl

# Create user with UID and GID of user with access to local volume mount
RUN groupadd -g ${GID} www-data || groupmod -g ${GID} www-data && \
    useradd -u ${UID} -g ${GID} -d /usr/local/apache2/htdocs -s /bin/bash -M www-data || \
    usermod -u ${UID} -g ${GID} www-data

# Create necessary directories and files for WebDAV
RUN mkdir -p /usr/local/apache2/var /usr/local/apache2/htdocs/data && \
touch /usr/local/apache2/var/DavLock 

# overwrite httpd config file
COPY ./httpd-config.conf /usr/local/apache2/conf/httpd.conf

# Set permissions and ownership for apache and htdocs folder
RUN chown -R www-data:www-data /usr/local/apache2 && \
chmod -R 755 /usr/local/apache2/htdocs

# Expose the apache HTTP port
EXPOSE 8081

# Run Apache HTTP Server in the foreground
USER www-data
CMD ["httpd-foreground"]
```


we need to configre `node_config.yaml` as follows

```
# Whitelist URLs and/or IP addresses that the algorithm containers are
# allowed to reach using the http protocol.
whitelist:
  domains:
    - google.com
    - github.com
    - host.docker.internal # docker host ip (windows/mac)
  ips:
    - 172.17.0.1 # docker bridge ip (linux)
    - 8.8.8.8
    - apache-server
  ports:
    - 443
    - 8081

# Containers that are defined here are linked to the algorithm containers and
# can therefore be accessed when by the algorithm when it is running. Note that
# for using this option, the container with 'container_name' should already be
# started before the node is started.
docker_services:
    apache-server: apache-server
```

Note that this solution **does not use a bridge network** but uses the mechanisms provided by vantage6 for [whitelisting](https://docs.vantage6.ai/en/main/features/node/whitelisting.html) and [linking Docker containers](https://docs.vantage6.ai/en/main/features/node/linked_docker_service.html).

**Comment by dkapitan** [comment]
@bartvanb @mellesies @yannick-vinkesteijn 

Next issue that we need to tackle, is how we can secure and manage the access of the Apache Server WebDAV service for different collaborations. In our solution, we have the following `httpd-config.conf` for the Apache server:

```
ServerName localhost
Listen 8081
LogLevel debug

# Load necessary modules
LoadModule unixd_module modules/mod_unixd.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule dir_module modules/mod_dir.so
LoadModule dav_module modules/mod_dav.so
LoadModule dav_fs_module modules/mod_dav_fs.so
LoadModule log_config_module modules/mod_log_config.so

# Configure DAV lock database
DavLockDB "/usr/local/apache2/var/DavLock"

DocumentRoot "/usr/local/apache2/htdocs"

# Configure log files for the entire server
ErrorLog "/usr/local/apache2/logs/webdav_error.log"
CustomLog "/usr/local/apache2/logs/webdav_access.log" combined

<Directory "/usr/local/apache2/htdocs">
    Dav on
    Options Indexes FollowSymLinks
    AllowOverride None
    Require all granted
    # directoryIndex bug: https://bz.apache.org/bugzilla/show_bug.cgi?id=54914
    DirectoryIndex disabled
    # turn of http setup so only webdav can be used for this directory
    <LimitExcept GET POST PUT DELETE>
        Require all granted
    </LimitExcept>
</Directory>
```

We can configure separate user folders (e.g. per collaoboration) and also shared (read-only) folders with Apache Server and WebDAV, as per [this example](https://hexeract.wordpress.com/2011/02/25/configure-a-webdav-enabled-webserver-for-multiple-user-folders-and-one-shared-folder/).

**Comment by bartvanb** [comment]
Thanks for posting back the solution! 

I noticed that in you node config yaml, you are still whitelisting some addresses like `google.com` and `8.8.8.8` - these are examples from the documentation and I think you should remove everything that you don't need there (I'll also clarify the docs so that this is clearer).
