### ISSUE TITLE
[Feature Request] package version on vantage6 module

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#1231]
Allow the following, similar to what pandas has:
```
import vantage6
vantage6.__version__
```

**Comment by bartvanb** [comment]
We already have it but it's at a slightly different location

```
>>> import vantage6.cli
>>> vantage6.cli.__version__
'4.4.0'
```

I think it's better to keep it there, since you may have a different version installed of CLI, algorithm tools, client etc. It would be confusing if `vantage6.version` gave a different answer than `vantage6.client.version` but with current it's clear that it concerns the CLI.
