### ISSUE TITLE
Python client: Create a node with name

### ISSUE THREAD

**Issue by stefan-wolfsheimer** [vantage6/vantage6#236]
The python client offers a method to create nodes for a collaboration and organization. The method does not accept the name parameter. To set the name an additional update operation is required:
```
cnode = client.node.create(collaboration=collab_id, organization=orga_id)
name = "node001"
client.node.update(cnode.get("id"), name=name)
```

It would be clearer if the API accepted the same fields for both operations (create and update). 

The POST operation for /api/node accepts a JSON payload (according to the SWAGGER apidoc just the collaboration_id).
I tried to create it with:
```
{
  "collaboration_id": 1,
  "organization_id": 3,
  "name": "testnode"
}
```
The name provided name is ignored and needs to be changed afterward.

Furthermore, the api_key can only be set via the shell (not with the client nor the REST API). Is this not possible for security reasons?

**Comment by bartvanb** [comment]
I agree this is an inconsistency between the create and update requests.

Indeed the API key should not be settable as any string by the user. This should be a UUID that is created when creating the node (or reset later). I think we should consider modifying the shell but I'd like to discuss internally as I'm not too familiar with the shell.

So that would give the following action points:
- [ ] Accept `name` as argument in creating node
- [ ] Adapt swagger for POST node to reflect that `organization_id` should be included and `name` may be included
- [ ] Discuss what to do with setting API key in the shell.

**Comment by bartvanb** [comment]
We will leave the shell options as is for now: the shell can only be accessed by the server admin (since you need access to the server machine). With the client and REST API you can not set the API key, but you can *re*set it. This leads to the server generating a new key.
