### ISSUE TITLE
[Bug] Creating a node for a non existant collaboration leads to a wrong error message

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#276]
**Describe the bug**
I get the error `Organization id=1 already has a node for collaboration id=1` even though there is not a single node in the database.

**To Reproduce**
Create a node for a collaboration that not exists:
```python
client.node.create(organization=1, collaboration=1, name='some-name')
Making request: POST | http://127.0.0.1:5000/node | None
Server responded with error code: 400
msg:Organization id=1 already has a node for collaboration id=1
```

It seems like the validation of the collaboration at https://github.com/vantage6/vantage6/blob/d462cf3e0bf8b246c667abe999f8377b3e8bd228/vantage6-server/vantage6/server/resource/node.py#L264 does not work.

**Comment by bartvanb** [comment]
I can't reproduce this, and get expected behaviour (error message saying the collaboration doesn't exist). Couldn't reproduce with either an existing server where I enter a non-existing collaboration or a brand-new server that has 0 collaborations. 
@frankcorneliusmartin can you check if you still encounter this issue?

**Comment by frankcorneliusmartin** [comment]
I am also not able to reproduce it anymore...
