### ISSUE TITLE
[Feature Request] Algorithm Template

### ISSUE THREAD

**Issue by arturomoncadatorres** [vantage6/vantage6#400]
**Problem description**
It can be cumbersome to get the file structure right when developing a new algorithm

**Desired solution**
It would be great to have a template that could have all the initial files required, so that the developer can focus only on the actual development and the algorithm and doesn't need to spend so much on the things around it

**Additional context**
There is an existing [boilerplate](https://github.com/IKNL/v6-boilerplate-py) for vantage6. However, it is outdated and still requires some fiddling to get it right.

**Comment by bartvanb** [comment]
A few updates on this:

- We now intend to use `copier` instead of `cookiecutter`. The main reason to do so is the `copier update` functionality that allows you to update an algorithm when the template is updated.
- Work-in-progress repo is here: https://github.com/vantage6/v6-algorithm-template

- [ ] clean up cookiecutter repo
- [ ] Create CLI command `v6 algorithm create`
- [ ] Create CLI command `v6 algorithm update`
- [ ] Ensure that there is a (CLI) command to submit an algorithm to the store from the template

**Comment by bartvanb** [comment]
Note that the CLI changes from #877 are necessary to implement the CLI part of this issue.

**Comment by frankcorneliusmartin** [comment]
Tested. 

@bartvanb do we need to keep this issue open? As there are some open todos?
