### ISSUE TITLE
[Change Request] Print full stacktrace instead of just the error when an error is encountered

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#675]
When a task results in an error I now get something like:
`warn > Error encountered while calling run_v6: 'ContainerClient' object has no attribute 'task'
`
Though this is useful to know, I sometimes have no idea where in the code it is triggered, especially if the error is general such as "index expects int, not str"

It would help a lot to speed up debugging and development to print the full stacktrace upon encountering an error in the execution of a task.

**Comment by bartvanb** [comment]
We decided not to do this always, as the error logs of certain algorithms may contain sensitive data. Therefore, there is now an option to set this called `print_full_error` (False by default).
In v4, we'll make it True by default. This is not done now because existing algorithms may then leak sensitive data. For v4, algorithms should be built again so then it is a good moment to switch that.

Will be released with v3.9
