### ISSUE TITLE
[Bug] starting container with vpn takes a lot of time

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#681]
**Describe the bug**
Starting a container on a node that has vpn enabled takes about 3 minutes more than starting it on the same node with vpn disabled.

**To Reproduce**
With vpn_subnet in the node config, start the node, run a task. Use the portal UI to see start and finish time of the task.

Comment out the vpn_subnet line in the config. Repeat the above.
See that without the vpn configured the task takes about 3 minutes less.

**Comment by frankcorneliusmartin** [comment]
Possible solution to randomize port selection and check if its free.

**Comment by frankcorneliusmartin** [comment]
From the iptables MAN
> -L, --list [chain]
List all rules in the selected chain. If no chain is selected, all chains are listed. As every other iptables command, it applies to the specified table (filter is the default), so NAT rules get listed by
iptables -t nat -n -L
Please note that it is often used with the -n option, in order to avoid long reverse DNS lookups.
