### ISSUE TITLE
[Change Request] Update ClientMockProtocol

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#683]
**Description**
The ClientMockProtocol is a nice feature that allows to locally test part of the algorithm. It would be helpful if it would get some maintenance and some additional features:

- remove the print statement from the mockclient.get_results() method. It makes more sense to print the output of the call rather than auto-assume a user wants a subresult (which could be bytes) printed
- unify the apis with the algorithmclient, such that it also has e.g. .task.create
- allow to provide the data itself directly into the datasets argument of the ClientMockProtocol constructor. This way we can use mock data initialized in Python for e.g. unit tests rather than depending on files on a harddisk (which is now also limited to csv)
- provide a way to extract the mock node id from within the mock method execution such that we can also simulate writing to the docker container temp folder for each unique node. e.g. an option would be to set an attribute org_id/node_id on the ClientMockProtocol that is updated before the call to method(). --> ideally this attribute is also added to the algorithmclient itself (now the only option to get it there is to use the jwt token, right?)

**Comment by bartvanb** [comment]
Preliminary work on branch `feature/mock-client-update`

- [ ] Made interface similar to other clients
- [ ] Removed print statement detailed above
- [ ] Added new functionality to mock eg VPN features, but also node IDs
- [ ] Make MockClient compatible with multiple data sources
- [ ] Adapt MockClient to v4 - or put this in the task list for v4

**Comment by harmbuisman** [comment]
To confirm, with the new changes I can change the following

Now:
MockClient
``` 
child_task = mockclient.create_new_task(
                    organization_ids=org_ids,
                    input_=input_,
                )
```

AlgorithmClient
```
 child_task = algorithm_client.task.create(
                organization_ids=child_nodes,
                name=str(transformer),
                description=str(transformer),
                input_=self.get_task_input_(server_round),
            )

```

to something like this?

```
def create_task(client, organization_ids, input_, name="", description="")
           return client.task.create(
                organization_ids=organization_ids,
                name=name,
                description=description,
                input_=input_,
            )

# MockClient
child_task = create_task(mockclient, ...)

# AlgorithmClient
child_task = create_task(algorithm_client, ...)

```

**Comment by bartvanb** [comment]
Yes it will be similar to that indeed. Only the `create_task()` function will look a bit different as the `client.task.create()` args will be a bit different for the MockClient and AlgorithmClient (e.g. MockClient doesn't accept a `name` or `description` arg)

**Comment by harmbuisman** [comment]
If it doesn't have the the same args, then the above is not possible. Can you add those args to MockClient as well, because I want to reduce the amount of duplicate code that I need to write to mock an algorithmclient.

**Comment by bartvanb** [comment]
Right, I just added `*args, **kwargs` to `client.task.create()` in the mock client, so that the above should work. I also checked that there were no other functions in the MockCLient that may be incompatible with their non-mocked counterparts.

Note that there are a couple of functions in the MockClient that have extra (always optional) arguments compared to the non-mocked functions. An example is `client.node.get()`, where in the mock client you can set whether it is online or not. But this should not lead to incompatibilities. You can always set properties of the mocked JSON response in the mock code.

**Comment by bartvanb** [comment]
Also, I now synced the return values of MockClient and AlgorithmClient. Before, mock endpoints returned only a part of the fields the real client returned. Now, the mock client also returns mock values for those (e.g. `client.node.get()` now also returns a `last_seen` attribute for mock client).
Note that most of these attributes are probably not very useful to algorithm developers, but we just included them all so that nothing is missing.
