### ISSUE TITLE
[Feature Request] `client.vpn.get_addresses` does not support _only_ parameters of the endpoint

### ISSUE THREAD

**Issue by frankcorneliusmartin** [vantage6/vantage6#729]
**Problem description**
In the python client I am not able to use the _only_ parameters: https://petronas.[vantage6](https://petronas.vantage6.ai/apidocs/#/VPN/get_vpn_algorithm_addresses).ai/apidocs/#/VPN/get_vpn_algorithm_addresses

**Desired solution**
Add both options to the python client

**Comment by frankcorneliusmartin** [comment]
We also want to get sibling container addresses

**Comment by bartvanb** [comment]
And add the 'my_own_address' functionality as well. As mentioned in the community meeting, current algorithms have a strategy where the central part sends their own address to the subtasks so this would be useful.

**Comment by bartvanb** [comment]
To address the original question: you cannot add the `only_*` parameters in the python client because *this endpoint is only accessible to containers* (in the same run). However, from later comments there are a few TODOs

- [ ] Add option to request sibling addresses
- [ ] Add option to request own address
