### ISSUE TITLE
Unexpected behaviour algorithm_client.vpn.get_parent_address

### ISSUE THREAD

**Issue by harmbuisman** [vantage6/vantage6#900]
algorithm_client.vpn.get_parent_address() returns a list rather than a string which I expected from the name or a dict which the docstring suggests, e.g. I now get this output:
 [{'port': 49167, 'label': '= message_queue', 'ip': 'XXX, 'organization_id': 3, 'task_id': 118, 'parent_id': None},
  {'port': 49168, 'label': '= algorithm_communication', 'ip': 'XXX', 'organization_id': 3, 'task_id': 118, 'parent_id': None},
  {'port': 49169, 'label': '= other_label', 'ip': 'XXX', 'organization_id': 3, 'task_id': 118, 'parent_id': None}]

I would have expected a string with the address in it. We have multiple ports exposed in the docker config file with labels that represent what we see here.

The docstring says the return type is a dict.

Suggestions:
* if this is a bug, then fix
* update the docstring to reflect the expected output, including the keys of the dict part that is returned
* rename the function to something like get_parent_address_info to better reflect that one gets more than just the ip address
* the label, e.g. '= algorithm_communication' seems a bug, I think it should be 'algorithm_communication'

The same applies to the other get_address functions.

**Comment by bartvanb** [comment]
Hi Harm,
- The return type according to the docs is wrong indeed, it should be `list[dict]` as you get one address per communication channel. So docstring should be updated
- I will not modify the function name as this will mean that 4.x will not be compatible with 4.0, and other people using this function would have to fix their algorithms. I can however add a FIXME so that we change the names in v5
- The labels starting with `= ` are I think likely caused by the labels in your Dockerfile. If you have `LABEL x = 'something'`, I think this needs to become `LABEL x='something'` - spacing is important apparently. I'll also adapt that in our boilerplate + template generator

**Comment by harmbuisman** [comment]
I saw the changes, what I meant is if the signature of the dict that is returned can be added, which is if I drill down in the code:

            d = {
                'port': port.port,
                'label': port.label,
                'ip': port.run.node.ip,
                'organization_id': port.run.organization_id,
                'task_id': port.run.task_id,
                'parent_id': port.run.task.parent_id,
            }
